/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

typedef struct {
  int sqp_stop_crit;
  int n_sqp_iter;
  int n_ls;
  int n_max_ls;
  int n_qp_iter;
  int n_max_qp_iter;
  double runtime;
}solver_stats;
const solver_stats* ocpfun_stats();

int ocpfun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ocpfun_alloc_mem(void);
int ocpfun_init_mem(int mem);
void ocpfun_free_mem(int mem);
int ocpfun_checkout(void);
void ocpfun_release(int mem);
void ocpfun_incref(void);
void ocpfun_decref(void);
casadi_int ocpfun_n_in(void);
casadi_int ocpfun_n_out(void);
casadi_real ocpfun_default_in(casadi_int i);
const char* ocpfun_name_in(casadi_int i);
const char* ocpfun_name_out(casadi_int i);
const casadi_int* ocpfun_sparsity_in(casadi_int i);
const casadi_int* ocpfun_sparsity_out(casadi_int i);
int ocpfun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ocpfun_SZ_ARG 273
#define ocpfun_SZ_RES 269
#define ocpfun_SZ_IW 2815
#define ocpfun_SZ_W 30175
#ifdef __cplusplus
} /* extern "C" */
#endif
